Added translations support (i18n)
DIYgod/RSSHub-Radar pull request #695
Opened 2022-05-12 08:33 UTC by arraintxo

Hi @DIYgod ,

I added translations support to the extension as that would be useful for us and I saw a pair of issues requesting this feature. (https://github.com/DIYgod/RSSHub-Radar/issues/674 , https://github.com/DIYgod/RSSHub-Radar/issues/33)

Added features:
- Browser language is automatically detected
- Default / Fallback language set to chinese (eventhought, I think english might be a better idea) 
- Supported languages: chinese (default), english, basque and spanish

More languages can be added by creating a language json file for the language and importing it to the i18n.js file

2022-05-15 10:37 UTC, Rongronggg9 requested changes

2022-05-15 10:37 UTC, Rongronggg9 commented on src/translations/en.json
> +  "current page rss": "RSS on current site",
```suggestion
  "current page rss": "RSS on the current site",
```

2022-05-15 10:37 UTC, Rongronggg9 commented on src/translations/en.json
> +  "for more rules join us": "For more rules support, <a target=\"_blank\" href=\"https://docs.rsshub.app/joinus/\">join us</a>！",
```suggestion
  "for more rules join us": "For more rules support, <a target=\"_blank\" href=\"https://docs.rsshub.app/en/joinus/quick-start.html\">join us</a>！",
```

2022-05-15 10:37 UTC, Rongronggg9 commented on src/translations/en.json
> +  "join rsshub": "Participate in the <a href=\"https://docs.rsshub.app\"> to make everything RSS-able!",
```suggestion
  "join rsshub": "Participate in the <a href=\"https://docs.rsshub.app/en/\"> to make everything RSS-able!",
```

2022-05-15 10:37 UTC, Rongronggg9 commented on src/translations/es.json
> +  "for more rules join us": "Para más reglas <a target=\"_blank\" href=\"https://docs.rsshub.app/joinus/\">únete</a>！",
```suggestion
  "for more rules join us": "Para más reglas <a target=\"_blank\" href=\"https://docs.rsshub.app/en/joinus/quick-start.html\">únete</a>！",
```

2022-05-15 10:37 UTC, Rongronggg9 commented on src/translations/es.json
> +  "join rsshub": "Únete a <a href=\"https://docs.rsshub.app\">RSSHub</a> para hacer todo accesible mediante RSS!",
```suggestion
  "join rsshub": "Únete a <a href=\"https://docs.rsshub.app/en/\">RSSHub</a> para hacer todo accesible mediante RSS!",
```

2022-05-15 10:37 UTC, Rongronggg9 commented on src/js/common/i18n.js
> +i18n.defaultLocale = 'zh';
Why not `en`?

2022-05-15 10:37 UTC, Rongronggg9 commented on src/translations/en.json
> +  "sponsored development": "Sponsored development of RSSHub Radar: <a target=\"_blank\" href=\"https://docs.rsshub.app/en/support\">https://docs.rsshub.app/en/support</a>",
```suggestion
  "sponsored development": "Sponsored development of RSSHub Radar: <a target=\"_blank\" href=\"https://docs.rsshub.app/en/support/\">https://docs.rsshub.app/en/support/</a>",
```

2022-05-15 10:37 UTC, Rongronggg9 commented on src/translations/es.json
> +  "sponsored development": "Soporta el desarrollo de RSSHub Radar: <a target=\"_blank\" href=\"https://docs.rsshub.app/en/support\">https://docs.rsshub.app/en/support</a>",
```suggestion
  "sponsored development": "Soporta el desarrollo de RSSHub Radar: <a target=\"_blank\" href=\"https://docs.rsshub.app/en/support/\">https://docs.rsshub.app/en/support/</a>",
```

2022-05-15 10:37 UTC, Rongronggg9 commented on src/translations/eu.json
> +  "for more rules join us": "Arau gehiago jasatzeko <a target=\"_blank\" href=\"https://docs.rsshub.app/joinus/\">batu zaitez</a>!",
```suggestion
  "for more rules join us": "Arau gehiago jasatzeko <a target=\"_blank\" href=\"https://docs.rsshub.app/en/joinus/quick-start.html\">batu zaitez</a>!",
```

2022-05-15 10:37 UTC, Rongronggg9 commented on src/translations/eu.json
> +  "join rsshub": "Gehitu zure burua <a href=\"https://docs.rsshub.app\">RSSHub</a>-era dena RSS bitartez jaso ahal izateko!",
```suggestion
  "join rsshub": "Gehitu zure burua <a href=\"https://docs.rsshub.app/en/\">RSSHub</a>-era dena RSS bitartez jaso ahal izateko!",
```

2022-05-15 10:37 UTC, Rongronggg9 commented on src/translations/eu.json
> +  "sponsored development": "RSSHub Radar laguntzeko: <a target=\"_blank\" href=\"https://docs.rsshub.app/en/support\">https://docs.rsshub.app/en/support</a>",
```suggestion
  "sponsored development": "RSSHub Radar laguntzeko: <a target=\"_blank\" href=\"https://docs.rsshub.app/en/support/\">https://docs.rsshub.app/en/support/</a>",
```

2022-05-15 10:37 UTC, Rongronggg9 commented on src/translations/zh.json
> +  "for more rules join us": "更多规则支持中，快来<a target=\"_blank\" href=\"https://docs.rsshub.app/joinus/\">参与我们</a>吧！",
```suggestion
  "for more rules join us": "更多规则支持中，快来<a target=\"_blank\" href=\"https://docs.rsshub.app/joinus/quick-start.html\">参与我们</a>吧！",
```

2022-05-16 07:42 UTC, arraintxo commented on src/js/common/i18n.js
> +i18n.defaultLocale = 'zh';
I set `en` as default language

2022-05-22 20:34 UTC, merged